export const Types = {
    ASSIGN_VALIDATION_ERROR: "ASSIGN_VALIDATION_ERROR",
    ASSIGN_GENERAL_ERROR: "ASSIGN_GENERAL_ERROR",
    ASSIGN_SUCCESS_MESSAGE: "ASSIGN_SUCCESS_MESSAGE",
    HIDE_ALERT: "HIDE_ALERT",
    CLEAR_LOGS: "CLEAR_LOGS"
}