export const Types = {
    INITIALIZE_PURCHASES: "INITIALIZE_PURCHASES",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    ADD_PURCHASE_SUCCESS: "ADD_PURCHASE_SUCCESS",
    UPDATE_PURCHASE_SUCCESS: "UPDATE_PURCHASE_SUCCESS",
    DELETE_PURCHASE_SUCCESS: "DELETE_PURCHASE_SUCCESS",
    DELETE_BULK_PURCHASE_SUCCESS: "DELETE_BULK_PURCHASE_SUCCESS"
}