export const Types = {
    INITIALIZE_STOCKINCART: "INITIALIZE_STOCKINCART",
    ADD_STOCKINCART_SUCCESS: "ADD_STOCKINCART_SUCCESS",
    SEARCH_PRODUCT: "SEARCH_PRODUCT",
    UPDATE_STOCKINCART_SUCCESS: "UPDATE_STOCKINCART_SUCCESS",
    DELETE_STOCKINCART_SUCCESS: "DELETE_STOCKINCART_SUCCESS",
    DELETE_BULK_STOCKINCART_SUCCESS: "DELETE_BULK_STOCKINCART_SUCCESS"
}