export const Types = {
    INITIALIZE_USERS: "INITIALIZE_USERS",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS"
}